### ISSUE TITLE
Plan for releasing other models

### ISSUE THREAD

**Issue by wjhou** [Stanford-AIMI/GREEN#1]
Hi, 

Thanks for your contributions.

I try the LLAMA version of GREEN which is just amazing. Do you plan to release other models (e.g., the Phi2 models)?

Best,
Ethan

**Comment by jbdel** [comment]
The readme contains links to other models.

Thanks!
JB

**Comment by wjhou** [comment]
Thank you for your reply.

The current link for radphi2 is https://huggingface.co/%5BStanfordAIMI/GREEN-RadPhi2 with an extra `%5B` which is invalid。

Best,
Ethan
