### ISSUE TITLE
Summary issue : Model responses don't always include all errors categories causing crash

### ISSUE THREAD

**Issue by rkassana** [Stanford-AIMI/GREEN#6]
Hi,
Thanks for this very good paper and code. 

It seems the trained model (Green-RadPhi2) responses will not always includes all categories.
I believe the following line should be removed or it will crash with key error exceptions of missing categories when trying to compute clustering of error sentences. 
https://github.com/Stanford-AIMI/GREEN/blob/5035ca94bd54c99dda5009e53ebb4e5fab4abf15/green_score/green.py#L331

This dict is already initialized with all categories before.
This is probably due to the fact that I tested with hyps and refs that did not yield all error categories, for example : refs=["Interstitial opacities without changes."], hyps=["Interstitial opacities at bases with changes."]

**Comment by MohammedSB** [comment]
Yup, noticed this with llama2 too.
Sometimes, only one category is show.

**Comment by SophieOstmeier** [comment]
Makes sense! Will change. Thank you!
