### ISSUE TITLE
pip install downloads different files

### ISSUE THREAD

**Issue by jomoll** [Stanford-AIMI/GREEN#9]
Using "pip install green-score" downloaded a bunch of different files/file versions than the ones here in the repo. Using for example 
"mean, std, green_score_list, summary, result_df = GREEN(model_name, refs, hyps)"
wasn't possible with the pip module as the GREEN function there had different inputs (i.e. self, cuda, max_len=200, **kwargs).
I used the python version specified in the readme.
Cloning the repo and using the files there resolved the issue for me.
Attached is an image of the green.py file that was downloaded with pip

![image](https://github.com/user-attachments/assets/ffc87a6a-8329-4903-9b92-19d990f7f21a)

**Comment by jbdel** [comment]
hey,
the last version is pip install green-score==0.0.7
https://pypi.org/project/green-score/
For this last version we restricted python3.8 (Requires: Python <3.9, >=3.8) So most likely your python env was not 3.8 and downloaded another previosu version.

@SophieOstmeier needs to test the package further to see if we can port it to python >3.8

**Comment by jbdel** [comment]
uploaded https://pypi.org/project/green-score/0.0.8/ that releases some of the package version constraints. Tried on a clean env, works.
